# Generated by Django 2.1.5 on 2019-02-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='devices',
            new_name='device',
        ),
    ]
