# Generated by Django 2.1.5 on 2019-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190222_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device',
            field=models.CharField(max_length=50),
        ),
    ]
