# Generated by Django 2.1.5 on 2019-03-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190302_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='notification',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
