# Generated by Django 2.1.5 on 2019-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_device_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=4)),
                ('check_time', models.IntegerField()),
                ('ping_time', models.IntegerField()),
            ],
        ),
    ]
