# Generated by Django 2.1.5 on 2019-03-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='settings',
            new_name='setting',
        ),
    ]
