# Generated by Django 2.1.5 on 2019-03-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190307_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='interface',
            field=models.BooleanField(),
        ),
    ]
