# Generated by Django 2.1.5 on 2019-03-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190312_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='interface',
            field=models.CharField(max_length=4),
        ),
    ]
