# Generated by Django 2.1.7 on 2019-03-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190313_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
