# Generated by Django 2.1.7 on 2019-03-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190316_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='check_time',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='interface',
        ),
    ]
