# Generated by Django 2.1.7 on 2019-03-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190321_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='down_flag',
            field=models.BooleanField(),
        ),
    ]
