# Generated by Django 2.1.7 on 2019-03-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190321_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='down_flag',
            field=models.BooleanField(),
        ),
    ]
